#!/bin/bash
set -e
GAMEPATH="$HOME/.steam/steam/steamapps/common/Heroes of Might and Magic 5 Tribes of the East/bin"

print_help() {
    echo "Set the HOMM55 game client to the utility or the base one."
    echo "Usage:"
    echo "'homm55client sp' for singleplayer client"
    echo "'homm55client mp' for the multiplayer one with ai functionality"
}

if [[ $# != 1 ]]; then
    echo "Error: needs exactly one argument"
    echo ""
    print_help
    exit 1
fi

if [[ $1 == "sp" ]]; then
    cp "$GAMEPATH/MMH55_64.exe" "$GAMEPATH/H5_Game.exe"
    echo "Singleplayer client is now active"
elif [[ $1 == "mp" ]]; then
    cp "$GAMEPATH/MMH55_Utility_64.exe" "$GAMEPATH/H5_Game.exe"
    echo "Multiplayer client is now active"
fi
