#!/bin/bash
pactl load-module module-null-sink sink_name="obs_stream_sink" sink_properties=device.description="obs_stream"
pactl load-module module-loopback source=obs_stream_sink.monitor sink=alsa_output.pci-0000_29_00.0.analog-stereo rate=48000
